# Train the model

In [6]:
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle, os
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import callbacks

In [7]:
df = pd.read_csv('dataset/csv/ds_cctv_v1.csv')

In [8]:
df.head(3)

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,y74,z74,v74,x75,y75,z75,v75,face_d15,face_s15,hand_s15
0,Nutup Muka,0.469739,0.578589,-0.127777,0.993265,0.440848,0.569411,-0.112306,0.994901,0.439771,...,0.711073,-0.029289,0.473242,0.495799,0.711073,-0.029289,0.473242,0.0,1.0,1.0
1,Nutup Muka,0.445407,0.614889,0.017926,0.995142,0.429321,0.619205,-0.039531,0.995156,0.433832,...,0.570589,0.175774,0.242573,0.472730,0.570589,0.175774,0.242573,0.0,0.0,0.0
2,Nutup Muka,0.445444,0.615121,-0.014786,0.997897,0.430551,0.620001,-0.072877,0.998852,0.432003,...,0.573695,0.211646,0.227217,0.469184,0.573695,0.211646,0.227217,0.0,0.0,0.0


In [5]:
df['class'].value_counts()

class
Nutup Muka    30
Diam          30
Celinguk      30
Name: count, dtype: int64

In [1]:
X = df.drop(['class'], axis=1)
y = df['class'] # target value

NameError: name 'df' is not defined

In [11]:
# X_train

In [12]:
encoder = LabelEncoder()
y_enc = encoder.fit_transform(y)

In [82]:
print(f"Encoded data : \n{y_enc[:5]}")
print(f"Reaaal data : \n{y[:5]}")

Encoded data : 
[2 2 2 2 2]
Reaaal data : 
0    Nutup Muka
1    Nutup Muka
2    Nutup Muka
3    Nutup Muka
4    Nutup Muka
Name: class, dtype: object


In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y_enc, test_size=0.15, random_state=1234, stratify=y_enc)

print(f"Train set size: {X_train.shape[0]}")
print(f"Test set size: {X_test.shape[0]}")

Train set size: 76
Test set size: 14


In [84]:
y_train[:5]

array([1, 2, 2, 1, 0])

In [94]:
MODEL_INPUT_SHAPE = (342,)
MODEL_TOTAL_OUTPUT = len(np.unique(y_train))
BEST_MODEL_PATH = "../Model/cnn/v1_cnn_model.h5"

In [95]:
print(MODEL_INPUT_SHAPE, MODEL_TOTAL_OUTPUT)

(342,) 3


In [96]:
checkpoint_cb = callbacks.ModelCheckpoint(
    filepath=BEST_MODEL_PATH,
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",                      
)

earlystop_cb = callbacks.EarlyStopping(
    monitor="val_accuracy",
    patience=5,
)

In [97]:
model = models.Sequential([
    layers.Dense(16, input_shape=MODEL_INPUT_SHAPE, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(len(np.unique(y_train)), activation='softmax'),
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

d:\Project Coding\Research\suspicious_detection_cctv\venv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [98]:
model.fit(
    X_train, y_train, 
    epochs=30,
    validation_split=0.2,
    callbacks=[checkpoint_cb, earlystop_cb])

Epoch 1/30


1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 595ms/step - accuracy: 0.2188 - loss: 1.1872

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 174ms/step - accuracy: 0.2285 - loss: 1.1922 - val_accuracy: 0.3125 - val_loss: 1.0964
Epoch 2/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3146 - loss: 1.1432 - val_accuracy: 0.3125 - val_loss: 1.0864
Epoch 3/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3257 - loss: 1.0968 - val_accuracy: 0.2500 - val_loss: 1.0877
Epoch 4/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3160 - loss: 1.0893 - val_accuracy: 0.2500 - val_loss: 1.0896
Epoch 5/30
1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.2812 - loss: 1.0931

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.3493 - loss: 1.0832 - val_accuracy: 0.4375 - val_loss: 1.0812
Epoch 6/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4889 - loss: 1.0688 - val_accuracy: 0.4375 - val_loss: 1.0709
Epoch 7/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5424 - loss: 1.0583 - val_accuracy: 0.4375 - val_loss: 1.0590
Epoch 8/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5757 - loss: 1.0495 - val_accuracy: 0.3750 - val_loss: 1.0544
Epoch 9/30
1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6250 - loss: 1.0442

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6194 - loss: 1.0420 - val_accuracy: 0.5000 - val_loss: 1.0485
Epoch 10/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5972 - loss: 1.0280 - val_accuracy: 0.5000 - val_loss: 1.0357
Epoch 11/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5437 - loss: 1.0236 - val_accuracy: 0.5000 - val_loss: 1.0209
Epoch 12/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5542 - loss: 1.0166 - val_accuracy: 0.5000 - val_loss: 1.0075
Epoch 13/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6181 - loss: 0.9926 - val_accuracy: 0.4375 - val_loss: 0.9926
Epoch 14/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5875 - loss: 0.9903 - val_accuracy: 0.4375 - val_loss: 0.9846


In [99]:
best_model = models.load_model(BEST_MODEL_PATH)

In [100]:
best_model.evaluate(X_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.6429 - loss: 1.0502


[1.0502249002456665, 0.6428571343421936]

In [101]:
TEST_DATA = X_test.iloc[0].to_numpy().reshape(1, -1)
best_model.predict(TEST_DATA)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[0.28922337, 0.36851364, 0.34226295]], dtype=float32)

In [102]:
def predict(data, model_path, encoder):
    model = models.load_model(model_path)
    pred = model.predict(data)
    output = np.argmax(pred, axis=1)
    output_label = encoder.inverse_transform(output)
    return output_label[0]


In [103]:
predict(TEST_DATA, BEST_MODEL_PATH, encoder=encoder)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


'Diam'

In [ ]:
# Set the threshold for positive detection
threshold = 0.75

# Get the predicted probabilities for the test set
y_pred_proba = model.predict_proba(X_test)[:, 1]

# Apply the threshold to get binary predictions
y_pred = (y_pred_proba >= threshold).astype(int)

# Convert y_test to binary format (1 for positive class, 0 for negative class)
y_test_binary = (y_test == 'positive_class').astype(int)  # Replace 'positive_class' with the actual positive class label


# Generate confusion matrix
cm = confusion_matrix(y_test_binary, y_pred)
TN, FP, FN, TP = cm.ravel()

print("True Positive (TP):", TP)
print("False Positive (FP):", FP)
print("True Negative (TN):", TN)
print("False Negative (FN):", FN)

AttributeError: 'Sequential' object has no attribute 'predict_proba'

: 